package chatsystem;

import interfaces.*;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import signals.FileProposal;

/**
 *
 * @author seb
 */
public class GUI extends javax.swing.JFrame implements CtrlToGUI {
    
    /**
     * Creates new form EntryFrame
     */
    private StyledDocument doc;
    private Style chatSystemStyle, errorStyle, receiveStyle, sendStyle;
    private File file; // the file we propose
    private ArrayList<String> receiverList; // receiverlist donné au ctrl
    private String fileHandled;// file that we are handling
    
    public GUI() {
        initComponents();
        doc = receivedMessageArea.getStyledDocument();
        
        // initialisation des styles de police utilisé
        // rouge pour le System
        // bleu pour un message recu
        // noir pour les messages envoyé
        chatSystemStyle = receivedMessageArea.addStyle("chatSystemStyle", null);
        receiveStyle = receivedMessageArea.addStyle("fromStyle", null);
        sendStyle = receivedMessageArea.addStyle("toStyle", null);
        errorStyle = receivedMessageArea.addStyle("errStyle", null);
        StyleConstants.setForeground(errorStyle, Color.RED);
        StyleConstants.setForeground(chatSystemStyle,Color.GREEN);
        StyleConstants.setForeground(receiveStyle, Color.YELLOW);
        StyleConstants.setForeground(sendStyle, Color.ORANGE);
        receiverList = new ArrayList<String>();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usageFrame = new javax.swing.JFrame();
        UsagePanel = new javax.swing.JPanel();
        receivedMessagePanel = new javax.swing.JScrollPane();
        receivedMessageArea = new javax.swing.JTextPane();
        sendButton = new javax.swing.JButton();
        receiverTextField = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        sendMessagePanel = new javax.swing.JScrollPane();
        sendMessageArea = new javax.swing.JTextArea();
        showHideButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        userlistLabel = new javax.swing.JLabel();
        listPanel = new javax.swing.JScrollPane();
        connectedList = new javax.swing.JList();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        proposeOption = new javax.swing.JMenuItem();
        proposedOption = new javax.swing.JMenuItem();
        userlistMenu = new javax.swing.JMenu();
        showOption = new javax.swing.JMenuItem();
        hideOption = new javax.swing.JMenuItem();
        quitMenu = new javax.swing.JMenu();
        queryDialog = new javax.swing.JDialog();
        filePanel = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        noButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();
        scrolFilepanel = new javax.swing.JScrollPane();
        listFile = new javax.swing.JList();
        entryPanel = new javax.swing.JPanel();
        presentationLabel = new javax.swing.JLabel();
        usernameArea = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        proprietaryLabel = new javax.swing.JLabel();

        usageFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        usageFrame.setSize(new java.awt.Dimension(620, 520));

        UsagePanel.setBackground(new java.awt.Color(102, 102, 102));
        UsagePanel.setPreferredSize(new java.awt.Dimension(650, 447));

        receivedMessageArea.setEditable(false);
        receivedMessageArea.setBackground(new java.awt.Color(51, 51, 51));
        receivedMessageArea.setForeground(new java.awt.Color(255, 255, 255));
        receivedMessagePanel.setViewportView(receivedMessageArea);

        sendButton.setText("SEND");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        receiverTextField.setEditable(false);
        receiverTextField.setBackground(new java.awt.Color(51, 51, 51));
        receiverTextField.setForeground(new java.awt.Color(255, 255, 255));
        receiverTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        toLabel.setForeground(new java.awt.Color(255, 255, 255));
        toLabel.setText("To :");

        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setText("Message :");

        sendMessageArea.setBackground(new java.awt.Color(51, 51, 51));
        sendMessageArea.setColumns(20);
        sendMessageArea.setForeground(new java.awt.Color(255, 255, 255));
        sendMessageArea.setRows(5);
        sendMessageArea.setCaretColor(new java.awt.Color(255, 255, 255));
        sendMessageArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sendMessagePanel.setViewportView(sendMessageArea);

        showHideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsagePanelLayout = new javax.swing.GroupLayout(UsagePanel);
        UsagePanel.setLayout(UsagePanelLayout);
        UsagePanelLayout.setHorizontalGroup(
            UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UsagePanelLayout.createSequentialGroup()
                                .addComponent(toLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiverTextField))
                            .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(receivedMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UsagePanelLayout.createSequentialGroup()
                                    .addComponent(sendMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sendButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showHideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(messageLabel))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        UsagePanelLayout.setVerticalGroup(
            UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsagePanelLayout.createSequentialGroup()
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(receivedMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(showHideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLabel)
                    .addComponent(receiverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sendMessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(249, 249, 249))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        userlistLabel.setBackground(new java.awt.Color(51, 0, 0));
        userlistLabel.setForeground(new java.awt.Color(255, 255, 255));
        userlistLabel.setText("Connected user");

        connectedList.setBackground(new java.awt.Color(51, 51, 51));
        connectedList.setForeground(new java.awt.Color(255, 255, 255));
        connectedList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connectedListMousePressed(evt);
            }
        });
        listPanel.setViewportView(connectedList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(userlistLabel)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(userlistLabel)
                .addGap(18, 18, 18)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        proposeOption.setText("Send File");
        proposeOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proposeOptionActionPerformed(evt);
            }
        });
        fileMenu.add(proposeOption);

        proposedOption.setText("See Files");
        proposedOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proposedOptionActionPerformed(evt);
            }
        });
        fileMenu.add(proposedOption);

        menuBar.add(fileMenu);

        userlistMenu.setText("Userlist");

        showOption.setText("Show");
        showOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOptionActionPerformed(evt);
            }
        });
        userlistMenu.add(showOption);

        hideOption.setText("Hide");
        hideOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideOptionActionPerformed(evt);
            }
        });
        userlistMenu.add(hideOption);

        menuBar.add(userlistMenu);

        quitMenu.setText("Quit");
        quitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quitMenuMousePressed(evt);
            }
        });
        menuBar.add(quitMenu);

        usageFrame.setJMenuBar(menuBar);

        javax.swing.GroupLayout usageFrameLayout = new javax.swing.GroupLayout(usageFrame.getContentPane());
        usageFrame.getContentPane().setLayout(usageFrameLayout);
        usageFrameLayout.setHorizontalGroup(
            usageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usageFrameLayout.createSequentialGroup()
                .addComponent(UsagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usageFrameLayout.setVerticalGroup(
            usageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        queryDialog.setBackground(new java.awt.Color(255, 255, 255));
        queryDialog.setSize(new java.awt.Dimension(524, 386));

        filePanel.setBackground(new java.awt.Color(51, 51, 51));

        questionLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionLabel.setText("   Do you accept to receive this file ?");

        noButton.setText("no");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        yesButton.setText("yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        listFile.setBackground(new java.awt.Color(0, 0, 0));
        listFile.setForeground(new java.awt.Color(255, 255, 255));
        listFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listFileMousePressed(evt);
            }
        });
        scrolFilepanel.setViewportView(listFile);

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(yesButton)
                        .addGap(60, 60, 60)
                        .addComponent(noButton))
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(scrolFilepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(questionLabel)
                .addGap(18, 18, 18)
                .addComponent(scrolFilepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout queryDialogLayout = new javax.swing.GroupLayout(queryDialog.getContentPane());
        queryDialog.getContentPane().setLayout(queryDialogLayout);
        queryDialogLayout.setHorizontalGroup(
            queryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        queryDialogLayout.setVerticalGroup(
            queryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entryPanel.setBackground(new java.awt.Color(51, 51, 51));

        presentationLabel.setBackground(new java.awt.Color(0, 0, 51));
        presentationLabel.setFont(new java.awt.Font("Malayalam MN", 2, 18)); // NOI18N
        presentationLabel.setForeground(new java.awt.Color(255, 255, 255));
        presentationLabel.setText("Welcome to the ChatSystem !");

        usernameArea.setBackground(new java.awt.Color(0, 0, 0));
        usernameArea.setForeground(new java.awt.Color(255, 255, 255));
        usernameArea.setText("username");
        usernameArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        usernameArea.setSelectedTextColor(new java.awt.Color(153, 153, 255));

        connectButton.setText("CONNECT");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        proprietaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        proprietaryLabel.setText("©RMS");

        javax.swing.GroupLayout entryPanelLayout = new javax.swing.GroupLayout(entryPanel);
        entryPanel.setLayout(entryPanelLayout);
        entryPanelLayout.setHorizontalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryPanelLayout.createSequentialGroup()
                .addGroup(entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proprietaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entryPanelLayout.createSequentialGroup()
                        .addGroup(entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(entryPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(presentationLabel))
                            .addGroup(entryPanelLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(connectButton)
                                    .addComponent(usernameArea, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        entryPanelLayout.setVerticalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(presentationLabel)
                .addGap(18, 18, 18)
                .addComponent(usernameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(proprietaryLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        System.out.println("DEBUG *** GUI : pressed CONNECT ***");
        ChatSystem.getControler().createLocalInfo(usernameArea.getText());
        usageFrame.setTitle("Welcome "+usernameArea.getText());
        connectedList.setModel(ChatSystem.getModel().getRemoteTable());
        connectedList.validate();
        listFile.setModel(ChatSystem.getModel().getFileStringProposed());
        ChatSystem.getControler().performConnect();
        
        try {
            doc.insertString(doc.getLength(), "Welcome to the chat ! \nyour adress ip is : " + ChatSystem.getModel().getLocalAdress() + "\n", chatSystemStyle);
        } catch (BadLocationException e) {
            System.err.println(e);
        }
        
        this.setVisible(false);
        this.usageFrame.setVisible(true);                      
    }//GEN-LAST:event_connectButtonActionPerformed
                
    
    /*
    *for query Dialog 
    */
    
    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
               
        System.out.println("DEBUG *** GUI : file accepted ***");
        queryDialog.setVisible(false);
        ChatSystem.getControler().processAcceptTransfer(fileHandled);
        fileHandled = null;
    }//GEN-LAST:event_yesButtonActionPerformed
    
    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
      
        System.out.println("DEBUG *** GUI : file refused ***");
        queryDialog.setVisible(false);
        ChatSystem.getControler().processRefuseTransfer(fileHandled);
        fileHandled = null;
    }//GEN-LAST:event_noButtonActionPerformed
    
    /*
    *for Usage frame 
    */
    
    private void connectedListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectedListMousePressed
        // TODO add your handling code here:
        System.out.println("DEBUG *** GUI : selected a receiver ***");
        if(!receiverList.contains((String) connectedList.getSelectedValue())){
            // si le user selectionné n'était pas déja selectionné
            System.out.println("DEBUG *** GUI : add to receivers ***");
            receiverList.add((String) connectedList.getSelectedValue());
            receiverTextField.setText(receiverList.toString());
        }else{
            System.out.println("DEBUG *** GUI : delete from receivers ***");
            receiverList.remove((String) connectedList.getSelectedValue());
        }
        receiverTextField.setText(arrayToString(receiverList));       
    }//GEN-LAST:event_connectedListMousePressed

    private void proposedOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proposedOptionActionPerformed
        // TODO add your handling code here:
        queryDialog.setVisible(true);
    }//GEN-LAST:event_proposedOptionActionPerformed

    private void quitMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitMenuMousePressed
        // TODO add your handling code here:
        System.out.println("DEBUG *** GUI : pressed DISCONNECT ***");
        ChatSystem.getControler().performDisconnect(ChatSystem.getModel().getUsername());
        receivedMessageArea.setText("");
        receiverTextField.setText("");
        usageFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_quitMenuMousePressed

    private void proposeOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proposeOptionActionPerformed
        // TODO add your handling code here:
        System.out.println("DEBUG *** GUI : pressed FILE ***");
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        sendMessageArea.setText("File : " + file.getAbsolutePath());
    }//GEN-LAST:event_proposeOptionActionPerformed

    private void showOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOptionActionPerformed
        // TODO add your handling code here:
        if (usageFrame.getWidth() < 700){
            usageFrame.setSize(usageFrame.getWidth()+ 230,usageFrame.getHeight());          
        }
    }//GEN-LAST:event_showOptionActionPerformed

    private void hideOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideOptionActionPerformed
        // TODO add your handling code here:
        if (usageFrame.getWidth() > 800){
            usageFrame.setSize(usageFrame.getWidth()- 230,usageFrame.getHeight());          
        }
    }//GEN-LAST:event_hideOptionActionPerformed

    private void showHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButtonActionPerformed
        // TODO add your handling code here:
        if (usageFrame.getWidth() < 700){
            usageFrame.setSize(usageFrame.getWidth()+ 230,usageFrame.getHeight());          
        }else if(usageFrame.getWidth() > 800){
            usageFrame.setSize(usageFrame.getWidth()- 230,usageFrame.getHeight());          
        }
    }//GEN-LAST:event_showHideButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
         System.out.println("DEBUG *** GUI : pressed SEND ***");
        
        if (receiverTextField.getText().equals("")) {
            // cas ou le remoteName n'est pas dans notre table
            System.err.println("DEBUG *** GUI : no such remote user ***");
            erreurReceiver();
        } else {
            // cas nominal on envoie la requete et on affiche dans notre boite de dialogue
            try {   
                for (String s : receiverList){
                    doc.insertString(doc.getLength(), "To " + s + " : " + sendMessageArea.getText() + "\n", sendStyle);
                }
                if(sendMessageArea.getText().contains("File :")){
                        System.out.println("DEBUG *** GUI : File transmitted to ctrl : " + sendMessageArea.getText() + " ***");
                        ChatSystem.getControler().performSendFile(file, receiverList);
                        file = null;
                    }else{
                        System.out.println("DEBUG *** GUI : message transmitted to ctrl : " + sendMessageArea.getText() + " ***");
                        ChatSystem.getControler().performSendMessage(sendMessageArea.getText(), receiverList);
                    }               
            } catch (BadLocationException e) {
                System.err.println(e);
            }
            sendMessageArea.setText("");
            receiverTextField.setText("");
            receiverList.clear();
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void listFileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFileMousePressed
        // TODO add your handling code here:
        System.out.println("DEBUG *** GUI : selected a file ***");              
         fileHandled = (String)listFile.getSelectedValue();     
            
    }//GEN-LAST:event_listFileMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UsagePanel;
    private javax.swing.JButton connectButton;
    private javax.swing.JList connectedList;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel filePanel;
    private javax.swing.JMenuItem hideOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList listFile;
    private javax.swing.JScrollPane listPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel presentationLabel;
    private javax.swing.JMenuItem proposeOption;
    private javax.swing.JMenuItem proposedOption;
    private javax.swing.JLabel proprietaryLabel;
    private javax.swing.JDialog queryDialog;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JMenu quitMenu;
    private javax.swing.JTextPane receivedMessageArea;
    private javax.swing.JScrollPane receivedMessagePanel;
    private javax.swing.JTextField receiverTextField;
    private javax.swing.JScrollPane scrolFilepanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea sendMessageArea;
    private javax.swing.JScrollPane sendMessagePanel;
    private javax.swing.JButton showHideButton;
    private javax.swing.JMenuItem showOption;
    private javax.swing.JLabel toLabel;
    private javax.swing.JFrame usageFrame;
    private javax.swing.JLabel userlistLabel;
    private javax.swing.JMenu userlistMenu;
    private javax.swing.JTextField usernameArea;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
    
    // toutes les fonctions à implémenter !
    @Override
    // appelé quand on recoit un hello ou hellook , il faut ajouter le nom a la list
    public void addUser(String remoteName) {
        System.out.println("DEBUG *** GUI : addUser <= when we receive a hello ***");
        
        try {
            doc.insertString(doc.getLength(), remoteName + " is now connected !\n", chatSystemStyle);
        } catch (BadLocationException e) {
            System.err.println(e);
        }
        connectedList.revalidate();
    }
    
    @Override
    // appelé quand on recoit un message
    public void processTextMessage(String message, String remoteName,ArrayList<String> to) {
        System.out.println("DEBUG *** GUI : processTextMessage <= when we receive a message ***");
        try {
            doc.insertString(doc.getLength(), "from " + remoteName + " : " + message + "\n", receiveStyle);
            if (to.size()>1){
                doc.insertString(doc.getLength(),"(sent to : "+arrayToString(to)+")\n" , receiveStyle);
            }
        } catch (BadLocationException e) {
            System.err.println(e);
        }
        System.out.println("DEBUG *** GUI : processTextMessage = "+message+" ***");
    }
    
    @Override
    // appelé quand le fichier est bien recu
    public void notifyTransmitted() {
        System.out.println("DEBUG *** GUI : notifyTransmitted <= when we have successfully received the file ***");
        
        try {
            doc.insertString(doc.getLength(), "File Transmitted ! " + "\n", chatSystemStyle);
        } catch (BadLocationException e) {
            System.err.println(e);
        }
    }
    
    @Override
    // appelé quand le fichier n'a pas été recu
    public void notifyNotTransmitted() {
        System.out.println("DEBUG *** GUI : notifyNotTransmitted <= when we haven't received the file ***");
        
        try {
            doc.insertString(doc.getLength(), "File failed to Transmit ! " + "\n", chatSystemStyle);
        } catch (BadLocationException e) {
            System.err.println(e);
        }
    }
    @Override
    //appelé quand on nous demande si on accepte la reception d'un fichier
    public void performFileQuery(FileProposal fp){
        //fileInfoTextArea.setText("File : " +fp.getFileName()+"\n File size : "+fp.getSize()+"\n From : "+fp.getFrom()+"\n");
        try {
            doc.insertString(doc.getLength(), "You received a knew file proposal !\n", chatSystemStyle);
            listFile.revalidate();
        } catch (BadLocationException e) {
            System.err.println(e);
        }
    }
    
    @Override
    // appelé par le ctrl quand on recoit un goodbye il faut supprimer le nom de la liste
    public void deleteUser(String remoteName) {
        System.out.println("DEBUG *** GUI : deleteUser <= when we receive a goodBye ***");
        
        //on supprime l'élément de notre list(que l'utilisateur voit) et on met a jour la liste
        try {
            doc.insertString(doc.getLength(), remoteName + " is now disconnected !\n", chatSystemStyle);
        } catch (BadLocationException e) {
            System.err.println(e);
        }
        
        //listModel.removeElement(remoteName);
        connectedList.revalidate();
    }
    /*
    fonction utiles dans selection receiver
    */
    
    public String arrayToString(ArrayList<String> a){
        String result =new String();
        for (String s : a){
            if(!(s == null)){
                result += s +",";
            }
        }
        return result;
    }
        
    public void erreurReceiver() {
        System.out.println("DEBUG *** GUI : erreurReceiver <= when we didn't choose any receiver ***");
        
        try {
            doc.insertString(doc.getLength(), "Erreur : selectionnez un utilisateur distant\n", errorStyle);
        } catch (BadLocationException e) {
            System.err.println(e);
        }
    }
}
