package chatsystem;
import chatsystem.*;
import java.awt.CardLayout;
import interfaces.*;
import javax.swing.DefaultListModel;
/**
 *
 * @author seb
 */
public class GUI_SEB extends javax.swing.JFrame implements CtrlToGUI{   
    /**
     * Creates new form EntryFrame
     */ 
    private static DefaultListModel listModel ; 
    public GUI_SEB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EntryPanel = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        usernameArea = new javax.swing.JTextField();
        UsagePanel = new javax.swing.JPanel();
        receivedMessagePanel = new javax.swing.JScrollPane();
        receivedMessageArea = new javax.swing.JEditorPane();
        sendMessagePanel = new javax.swing.JScrollPane();
        sendMessageArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        fileChooseButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();
        userlistLabel = new javax.swing.JLabel();
        listPanel = new javax.swing.JScrollPane();
        connectedList = new javax.swing.JList();
        nameInfoLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        EntryPanel.setPreferredSize(new java.awt.Dimension(200, 100));

        connectButton.setText("CONNECT");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        usernameArea.setText("username");
        usernameArea.setSelectedTextColor(new java.awt.Color(153, 153, 255));
        usernameArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EntryPanelLayout = new javax.swing.GroupLayout(EntryPanel);
        EntryPanel.setLayout(EntryPanelLayout);
        EntryPanelLayout.setHorizontalGroup(
            EntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryPanelLayout.createSequentialGroup()
                .addGroup(EntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntryPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(usernameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EntryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(connectButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        EntryPanelLayout.setVerticalGroup(
            EntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(usernameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(connectButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(EntryPanel);

        receivedMessagePanel.setViewportView(receivedMessageArea);

        sendMessageArea.setColumns(20);
        sendMessageArea.setRows(5);
        sendMessagePanel.setViewportView(sendMessageArea);

        sendButton.setText("SEND");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        fileChooseButton.setText("FILE");
        fileChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseButtonActionPerformed(evt);
            }
        });

        disconnectButton.setText("DISCONNECT");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        userlistLabel.setText("Connected user");

        listPanel.setViewportView(connectedList);

        nameInfoLabel.setText("My name :");

        usernameLabel.setText("username");

        javax.swing.GroupLayout UsagePanelLayout = new javax.swing.GroupLayout(UsagePanel);
        UsagePanel.setLayout(UsagePanelLayout);
        UsagePanelLayout.setHorizontalGroup(
            UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsagePanelLayout.createSequentialGroup()
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disconnectButton)
                            .addComponent(listPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(userlistLabel))
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receivedMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addComponent(sendMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fileChooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        UsagePanelLayout.setVerticalGroup(
            UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsagePanelLayout.createSequentialGroup()
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(receivedMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameInfoLabel)
                            .addComponent(usernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userlistLabel)
                        .addGap(18, 18, 18)
                        .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addGroup(UsagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UsagePanelLayout.createSequentialGroup()
                                .addComponent(sendButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fileChooseButton))
                            .addComponent(sendMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(UsagePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(disconnectButton)))
                .addContainerGap())
        );

        getContentPane().add(UsagePanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameAreaActionPerformed

    }//GEN-LAST:event_usernameAreaActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        ChatSystem.getControler().createLocalInfo(usernameArea.getText());
        listModel = new DefaultListModel();
        connectedList.setModel(listModel);
        connectedList.validate();
        ChatSystem.getControler().performConnect(usernameArea.getText());
        this.usernameLabel.setText(usernameArea.getText());
        this.receivedMessageArea.setText("your adress ip is : " + ChatSystem.getControler().getModel().getLocalAdress()+"\n");
        this.EntryPanel.setVisible(false);
        this.UsagePanel.setVisible(true);
    }//GEN-LAST:event_connectButtonActionPerformed
    
    
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        //ChatSystem.getControler().performSendMessage(sendMessageArea.getText(),"remotename");
        // il faut changer le "remoteName"
    }//GEN-LAST:event_sendButtonActionPerformed

    private void fileChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseButtonActionPerformed
        // TODO add your handling code here:
        System.err.println("NOT IMPLEMENTED");
    }//GEN-LAST:event_fileChooseButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        ChatSystem.getControler().performDisconnect(usernameLabel.getText());
        this.UsagePanel.setVisible(false);
        this.EntryPanel.setVisible(true);
        
    }//GEN-LAST:event_disconnectButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EntryPanel;
    private javax.swing.JPanel UsagePanel;
    private javax.swing.JButton connectButton;
    private javax.swing.JList connectedList;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton fileChooseButton;
    private javax.swing.JScrollPane listPanel;
    private javax.swing.JLabel nameInfoLabel;
    private javax.swing.JEditorPane receivedMessageArea;
    private javax.swing.JScrollPane receivedMessagePanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea sendMessageArea;
    private javax.swing.JScrollPane sendMessagePanel;
    private javax.swing.JLabel userlistLabel;
    private javax.swing.JTextField usernameArea;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    
    // toutes les fonctions à implémenter ! 
    
    @Override
    // appelé quand on recoit un hello ou hellook , il faut ajouter le nom a la list
    public void addUser(String remoteName) {   
        listModel.addElement(remoteName);
        connectedList.revalidate();
    }

    @Override
    public void processTextMessage(String message, String remoteName) {
        receivedMessageArea.setText("from " + remoteName + " : " + message +"\n");
    }

    @Override
    public void notifyTransmitted() {
        receivedMessageArea.setText("File Transmitted ! "+"\n");
    }

    @Override
    public void notifyNotTransmitted() {
        receivedMessageArea.setText("File transmission failed !"+"\n");
    }

    @Override
    // appelé par le ctrl quand on recoit un goodbye il faut supprimer le nom de la liste
    public void deleteUser(String remoteName) {
        listModel.removeElement(remoteName);
        connectedList.revalidate();
    }
}
